name: Build

on:
  schedule:
    #         ┌───────────── minute (0 - 59)
    #         │ ┌───────────── hour (0 - 23)
    #         │ │ ┌───────────── day of the month (1 - 31)
    #         │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #         │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #         │ │ │ │ │
    #         │ │ │ │ │
    #         │ │ │ │ │
    #         * * * * *
    - cron:  '0 0 * * SUN'

  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Check GitHub secrets
        shell: bash
        run: |
          ERROR="false"

          [[ "${{ secrets.DOCKERHUB_USERNAME }}" == "" ]] && ERROR="true" && echo "::error::Missing DOCKERHUB_USERNAME, check GitHub secrets"
          [[ "${{ secrets.DOCKERHUB_TOKEN }}" == "" ]]    && ERROR="true" && echo "::error::Missing DOCKERHUB_TOKEN, check GitHub secrets"

          if [[ "${ERROR}" == "true" ]]; then
            echo "::error::Please update GitHub secrets"
            exit 1
          else
            exit 0
          fi
      -
        uses: actions/checkout@v2
      -
        uses: docker/setup-qemu-action@v1
      -
        uses: docker/setup-buildx-action@v1
      -
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set docker tags and labels
        uses:  docker/metadata-action@v3
        id: meta
        with:
          images: "andrius/alpine-tor"
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=sha,enable=false
            type=ref,event=branch
            type=ref,event=tag
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
